<a href="https://colab.research.google.com/github/myielin/dataMiningUTFPR/blob/master/planeDelay/planepred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### imports e inicialização da base de dados

[link do repositório no Github](https://github.com/myielin/dataMiningUTFPR/tree/master/planeDelay)



In [6]:
import warnings
warnings.filterwarnings("ignore")

In [7]:
import pandas as pd

In [8]:
dados = pd.read_csv("https://raw.githubusercontent.com/myielin/dataMiningUTFPR/master/planeDelay/Airlines.csv")

In [9]:
dados.tail()

id Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  \
539378  539379      CO     178         OGG       SNA          5  1439     326   
539379  539380      FL     398         SEA       ATL          5  1439     305   
539380  539381      FL     609         SFO       MKE          5  1439     255   
539381  539382      UA      78         HNL       SFO          5  1439     313   
539382  539383      US    1442         LAX       PHL          5  1439     301   

        Delay  
539378      0  
539379      0  
539380      0  
539381      1  
539382      1

### Perguntas

**Qual a empresa aérea que possui maior quantidade de voos?**

In [13]:
# primeiro serão verificadas quais são as empresas do conjunto:

dados["Airline"].unique()

array(['CO', 'US', 'AA', 'AS', 'DL', 'B6', 'HA', 'OO', '9E', 'OH', 'EV',
       'XE', 'YV', 'UA', 'MQ', 'FL', 'F9', 'WN'], dtype=object)

In [14]:
# depois observar a quantidade de voos de cada:

dados["Airline"].value_counts()

WN    94097
DL    60940
OO    50254
AA    45656
MQ    36605
US    34500
XE    31126
EV    27983
UA    27619
CO    21118
FL    20827
9E    20686
B6    18112
YV    13725
OH    12630
AS    11471
F9     6456
HA     5578
Name: Airline, dtype: int64

verifica-se que a empresa com maior quantidade de voos é a Northwest Airlines (WN)

**Quais as malhas (Airport From e Airport To) que levam o tempo entre 500 e 1000?**

In [25]:
# criar o Subconjunto seguindo o padrão desejado e observar a distribuição de objetos

malhas = dados[(dados["Time"] >= 500) & (dados["Time"] <= 1000)]
malhas['Time'].value_counts()

540    3723
510    3700
660    3319
990    3158
525    3131
       ... 
546      67
549      62
658      59
558      54
594      37
Name: Time, Length: 501, dtype: int64

In [27]:
# mostrar quais malhas seguem o padrão pelo ID 

malhas["id"].unique()

array([  3091,   3092,   3093, ..., 535988, 535989, 535990])

Aparentemente os valores no intervalo de 3091 até 535990 se encaixam no padrão, então há como checar se existem excessões:

In [47]:
check = ((dados["Time"][3091:535990] < 500)|(dados["Time"][3091:535990] > 10000))
check.any()

True

In [48]:
check.sum()       # existem muitas excessões

90926

algumas malhas entre ID 3.091 até 535.990 seguem o padrão, e compõem o subconjunto _malhas_ 

**Quais as malhas (Airport From e Airport To)  que possuem a maior quantidade de voos? Apresentar ordenado do maior para o menor**

In [55]:
# como demonstrado acima, a ordem pode ser obtida através de:

malhas['AirportFrom'].value_counts()

ATL    20758
ORD    13075
DFW    12285
DEN    11265
PHX     9345
       ...  
ERI       17
SJT       15
STX       13
DBQ        2
PLN        1
Name: AirportFrom, Length: 285, dtype: int64

In [56]:
malhas['AirportTo'].value_counts()

ATL    18088
ORD    13099
DFW    12370
DEN    10252
IAH     8392
       ...  
PIE        3
ABR        2
PLN        1
MKG        1
CDC        1
Name: AirportTo, Length: 291, dtype: int64

**Qual a empresa aérea que possui a maior quantidade de voos com atraso**

In [58]:
atrasados = dados[dados["Delay"] == 1]
atrasados["Airline"].value_counts()

WN    65657
DL    27452
OO    22760
AA    17736
MQ    12742
CO    11957
XE    11795
US    11591
EV    11255
UA     8946
B6     8459
9E     8226
FL     6275
AS     3892
OH     3502
YV     3334
F9     2899
HA     1786
Name: Airline, dtype: int64